[package]
name = "boot-6502"
version = "0.1.0"
authors = ["Dragnmn <dragnmn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
panic-halt = "0.2.0"
arduino-mega2560 = { git = "https://github.com/Rahix/avr-hal" }
ufmt = "0.1.0"

[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"

