[package]
name = "boot-6502"
version = "0.1.0"
authors = ["Dragnmn <dragnmn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib-gpio = { path = './lib-gpio' }
lib-gpio-real = { path = './lib-gpio-real' }
boot = { path = './boot' }
anyhow = "1.0.32"
gpio-cdev = "0.4.0"