cargo-features = ["strip"]

[package]
name = "boot-6502"
version = "0.1.0"
authors = ["Dragnmn <dragnmn@gmail.com>"]
edition = "2018"

[dependencies]
# panic-halt = "0.2.0"
arduino-mega2560 = { git = "https://github.com/Rahix/avr-hal" }
atmega2560-hal = { git = "https://github.com/Rahix/avr-hal" }
avr-hal-generic = { git = "https://github.com/Rahix/avr-hal" }
ufmt = "0.1.0"

[profile.dev]
lto = true
opt-level = "s"
debug = true

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "s"
strip = "symbols"
