[package]
name = "boot-6502"
version = "0.1.0"
authors = ["Tim Evers <29369097+TVerse@users.noreply.github.com>"]
edition = "2018"

[dependencies]
lib-io = { path = "lib-io" }
lib-io-rpi = { path = "lib-io-rpi" }
sfota = { path = "../sfota" }
gpio-cdev = "0.4.0"
itertools = "0.9.0"
tempfile = "3.1.0"
anyhow = "1.0.33"

[dev-dependencies]
rand = "0.7.3"
