[package]
name = "boot"
version = "0.1.0"
authors = ["Dragnmn <dragnmn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib-gpio = { path = '../lib-gpio' }
anyhow = "1.0.31"
